@startuml

start

-StandardActivity#am_create_activity
-StandardActivity#am_focused_activity
-MainActivity#am_pause_activity
-MainActivity#am_on_paused_called
-StandardActivity#am_restart_activity
-StandardActivity#am_on_resume_called
-StandardActivity#am_activity_launch_time
-MainActivity#am_stop_activity
-MainActivity#am_on_stop_called

-StandardActivity#am_finish_activity
-MainActivity#am_focused_activity
-StandardActivity#am_pause_activity
-StandardActivity#am_on_paused_called
-MainActivity#am_resume_activity
-MainActivity#am_on_resume_called
-StandardActivity#am_destroy_activity
-StandardActivity#am_on_stop_called

stop

@enduml